### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by maxnowack** [welldan97/osx-app-spaces-manager#1]
Thank you for your awesome work! I think this is something I've search for a long time and this project looks very promising!
Unfortunately I don't know how I can use it.
Is it possible for you to write a very short description, how the CLI can be used and what the prerequisits are (e.g. `~/.osx-app-spaces-config.coffee`)?

**Comment by welldan97** [comment]
Haha, thank you very much! Never thought, someone would look at that, at least before I release it. I just made it for personal usage :). How you discovered it at all?

For sure I'll make a readme, later today, at max tomorrow.

**Comment by maxnowack** [comment]
Haha, I've been searching for a solution to automatically set up my workspace (e.g. open atom on 1st space, terminal on 2nd, etc.) for a while. Today, while searching on google, I've found this package on npm and eventually this repo :)

**Comment by welldan97** [comment]
Hey @maxnowack, I've just pushed Readme. I hope that helps. Don't hesitate to ask questions, if you have any.
